services:
  nexus-redis:
    image: redis:latest
    container_name: nexus-redis
    restart: unless-stopped
    command: redis-server ---save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - nexus-backend
    volumes:
      - redis_data:/redis_data
    healthCheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5